### ISSUE TITLE
Crashing with TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by drewavis** [matusnovak/doxybook#7]
Hello, I am attempting to parse doxygen output from a Python API, and I'm seeing this crash:

Parsing: indexpage
Deduplicating data... (may take a minute!)
Sorting...
Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\doxybook-script.py", line 11, in <module>
    load_entry_point('doxybook==3.1.1', 'console_scripts', 'doxybook')()
  File "C:\Program Files\Python38\lib\site-packages\doxybook-3.1.1-py3.8.egg\doxybook\__init__.py", line 74, in main
  File "C:\Program Files\Python38\lib\site-packages\doxybook-3.1.1-py3.8.egg\doxybook\runner.py", line 33, in run
  File "C:\Program Files\Python38\lib\site-packages\doxybook-3.1.1-py3.8.egg\doxybook\generator.py", line 55, in __init__
  File "C:\Program Files\Python38\lib\site-packages\jinja2\environment.py", line 938, in __new__
    env = get_spontaneous_environment(
  File "C:\Program Files\Python38\lib\site-packages\jinja2\environment.py", line 55, in get_spontaneous_environment
    _spontaneous_environments[args] = env = Environment(*args)
  File "C:\Program Files\Python38\lib\site-packages\jinja2\environment.py", line 338, in __init__
    _environment_sanity_check(self)
  File "C:\Program Files\Python38\lib\site-packages\jinja2\environment.py", line 102, in _environment_sanity_check
    assert issubclass(environment.undefined, Undefined), 'undefined must ' \
TypeError: issubclass() arg 1 must be a class

I'm using Python 3.8 / Windows, and am using the Master branch of doxybook.

**Comment by matusnovak** [comment]
Hi @drewavis 

I think I know where the problem is and I may have a fix. Would it be possible for you to pull the [bugfix-typerror-issubclass](https://github.com/matusnovak/doxybook/tree/bugfix-typerror-issubclass) branch, build it manually, and then try it if the error appears again?

Here are the steps to clone the branch locally and get it installed:

```bash
git clone https://github.com/matusnovak/doxybook.git
cd doxybook
git checkout bugfix-typerror-issubclass
python setup.py install
```

It should install under `C:\Python38\Scripts`.

**Comment by drewavis** [comment]
Thanks!  That issue seems to be fixed, but I'm getting a different one now:

Generating ..\source\py_ref_doxybook\class_max_plus_1_1_abstract_custom_action_item.md
Traceback (most recent call last):
  File "C:\Program Files\Python38\Scripts\doxybook-script.py", line 11, in <module>
    load_entry_point('doxybook==3.1.1', 'console_scripts', 'doxybook')()
  File "C:\Program Files\Python38\lib\site-packages\doxybook-3.1.1-py3.8.egg\doxybook\__init__.py", line 74, in main
  File "C:\Program Files\Python38\lib\site-packages\doxybook-3.1.1-py3.8.egg\doxybook\runner.py", line 36, in run
  File "C:\Program Files\Python38\lib\site-packages\doxybook-3.1.1-py3.8.egg\doxybook\generator.py", line 273, in members
  File "C:\Program Files\Python38\lib\site-packages\doxybook-3.1.1-py3.8.egg\doxybook\generator.py", line 252, in member
  File "C:\Program Files\Python38\lib\site-packages\doxybook-3.1.1-py3.8.egg\doxybook\generator.py", line 273, in members
  File "C:\Program Files\Python38\lib\site-packages\doxybook-3.1.1-py3.8.egg\doxybook\generator.py", line 249, in member
  File "C:\Program Files\Python38\lib\site-packages\doxybook-3.1.1-py3.8.egg\doxybook\generator.py", line 75, in _render
  File "C:\Program Files\Python38\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Program Files\Python38\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Program Files\Python38\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python38\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 43, in <module>
  File "C:\Program Files\Python38\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "C:\Program Files\Python38\lib\site-packages\doxybook-3.1.1-py3.8.egg\doxybook\node.py", line 642, in derived_classes
  File "C:\Program Files\Python38\lib\site-packages\doxybook-3.1.1-py3.8.egg\doxybook\cache.py", line 13, in get
IndexError: Key: class_max_plus_extend_1_1___custom_action_item not found in cache!

**Comment by matusnovak** [comment]
Hi @drewavis  

I will need the Doxygen generated XML files to check what exactly is wrong. Is your project open source? 

Alternatively, could you send me the XML files to my email? (You can find my email on my profile page https://github.com/matusnovak)

**Comment by ricktobacco** [comment]
Hi @matusnovak I am getting a similar error, on Ubuntu, when doing `doxybook -h`
Traceback (most recent call last):
  File "/usr/local/bin/doxybook", line 11, in <module>
    load_entry_point('doxybook==3.1.1', 'console_scripts', 'doxybook')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/doxybook/__init__.py", line 4, in <module>
  File "/usr/local/lib/python2.7/dist-packages/doxybook-3.1.1-py2.7.egg/doxybook/runner.py", line 10
    def run(output: str, 
                  ^
SyntaxError: invalid syntax

**Comment by matusnovak** [comment]
Hi @ricktobacco 

From your log: `/usr/local/lib/python2.7/dist-packages/` I believe you are using Python 2.7. This tool is limited to Python 3.6 or newer. Uninstall this package from Python 2, install Python 3, then try installing it explicitly as: `python3 -m pip install doxybook` (or `pip3 install doxybook` should work as well).

**Comment by ricktobacco** [comment]
All is working very nicely, almost flawlessly, but I see the same parameters appearing twice for macros although the doxygen docs don't have this issue:
![Screenshot from 2019-11-08 22-17-25](https://user-images.githubusercontent.com/17416373/68522183-6f9a4880-0276-11ea-82e4-1d510a96d0ec.png)
![Screenshot from 2019-11-08 22-17-42](https://user-images.githubusercontent.com/17416373/68522184-6f9a4880-0276-11ea-803e-493674971147.png)

**Comment by matusnovak** [comment]
@drewavis I have released a version with the fix for the issubclass() bug -> https://pypi.org/project/doxybook/3.1.3/

If you still have problem with the other issue please send me a link to your project or send me the doxygen XML files.
